In [1]:
import numpy as np
# checking the dimensions of my array use ndim
arr = np.array ([1,2,3,4])
 

In [2]:
print (arr)

[1 2 3 4]


In [3]:
arr.ndim

1

In [4]:
import numpy as np
range = np.arange (1,10)

In [6]:
range = np.arange (1,10)  

In [7]:
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print (range)

[1 2 3 4 5 6 7 8 9]


In [9]:
 range = np.arange (1,10, 2) """adding a thrd value gives a step"""

SyntaxError: invalid syntax (1971229035.py, line 1)

In [10]:
 range = np.arange (1,10, 2)

In [11]:
range

array([1, 3, 5, 7, 9])

In [12]:
np.linespace (0,1,10)

AttributeError: module 'numpy' has no attribute 'linespace'

In [13]:
arr = np.linespace (0,10,1)

AttributeError: module 'numpy' has no attribute 'linespace'

In [15]:
arr = np.linspace (0,10,1)
arr

array([0.])

 arr = np.logspace (1,3, 3)

In [16]:
 # starts from 10^1 and ends at 10^3 and give 4 values
arr = np.logspace(1,3,4)

In [17]:
arr

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [20]:
#np.zreos -> array full of zeros
arr = np.zeros ([5,3])
arr

#same thing with np.ones ([])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#np.full()->array full of any values
arr=np.full (2,1)
arr

array([1, 1])

In [22]:
#using np.full for higher order dimensions
arr= np.full ([2,4], 5)
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [23]:
# np.random.rand -> evenly distributees random floats 
arr = np.random.rand (2,10)
arr  #note for this do not enclose your dimensions in square brackets

array([[0.58264053, 0.0415277 , 0.75496959, 0.99086451, 0.76174326,
        0.47628489, 0.90740847, 0.02010398, 0.90236013, 0.50265673],
       [0.81485439, 0.73941528, 0.08120129, 0.17179921, 0.94682759,
        0.80885866, 0.86202801, 0.45622347, 0.43243119, 0.64709222]])

In [7]:
# fills array with ranom integers
arr = np.random.randint (2,4)
arr

2

In [10]:
arr = np.random.randint (2,3, size = (3))
arr

array([2, 2, 2], dtype=int32)

In [6]:
import numpy as np
arr = np.zeros ([2,3,4,1])
arr

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [10]:
arr=np.full ([2,4],7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
arr = np.random.rand(2,3,4) # for rand not putting square brackets is a must
arr

array([[[0.28434701, 0.65948338, 0.01999991, 0.82990652],
        [0.53899458, 0.25676758, 0.12773507, 0.03659115],
        [0.74700129, 0.15678571, 0.18671655, 0.40563332]],

       [[0.65435094, 0.3149559 , 0.16546939, 0.79650531],
        [0.36894847, 0.52454647, 0.32708993, 0.57708566],
        [0.42515518, 0.1396023 , 0.00533556, 0.84961176]]])

In [17]:
arr = np.random.randn (2,3)# this means that the mean would always
#be 0 and the standard deviation is gping to be 1
arr 

array([[ 0.56491443, -2.4632487 ,  0.55555202],
       [-1.0033551 , -0.91545007,  0.7488123 ]])

In [20]:
arr= np.random.randint (10,100,(2,4))
arr # start stop, size

array([[34, 52, 56, 44],
       [14, 34, 30, 62]], dtype=int32)

In [32]:
#numpy data types and type casting 
#arrays does notallows multiple data types to be stored in it
#instead precedence is giving to data types.
#string > floats >int
arr =  np.array([33.1,False,3,5.0],)
print (arr)
type (arr)

[ True False  True  True]


numpy.ndarray

In [ ]:
arr =  np.array([33.1,False,3,5.0], dtype=  bool)
print (arr)
type (arr) # use dtype to change the datatype of the 
#array
 

In [39]:
#astype converts one data type from one to the other 
#keeps the original data type constant and creates
#a new one 
new_arr = arr.astype(np.float64)
new_arrconverts
#astype(int or np.int64)  from one data type to int


array([1., 0., 1., 1.])

In [ ]:
#casting errors
#you cannot convert a string to another data type.
#.ndim= the number of rows of the array
#.shae the dimensions of the array
#.size = the multiple of the array
#.itemsize = the space in bytes of an individual object in the array



In [44]:
#array reshaping
arr = np.array ([2,3,5])
reshape = arr.reshape (3,1)
reshape

array([[2],
       [3],
       [5]])

In [46]:
#.ravel() to convert to 1D array
ravel = arr.ravel()
ravel

array([2, 3, 5])

In [47]:
#array functions
arr.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [52]:
from numpy import pi
np.sqrt(arr) # remember that this is a function that takes an argument
np.exp(arr) #exponential
np.sin([0,pi/2,pi/4])
#

array([0.        , 1.        , 0.70710678])

In [93]:
#indexing and slicing 
arr[-1]  # negative indexing gives the last element of the list
#negative indexing starts from the end of the list
#slicing
arr[0:3]#this is going to print the 
#elements fom zero but would exlude 3

array([ 1,  2, 23])

In [94]:
#note for negative slicing 
# you cannot start from a higher index to 
#a lower index without using steps 
arr
arr[-1,]

np.int64(5)

In [65]:
#multidimensional slicing
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
#to print the first two rows and all columns
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [67]:
#index arrays (np.take()) these are built in funtions to perform slicing
arrs= ([10,20,30,40,50,60])
cut = [0,3,4,5]
print(np.take(arrs,cut))


[10 40 50 60]


In [69]:
#iterating using nditer(). remember that you
#cannot iterate through an array using just loops
for x in np.nditer(arrs):
    print(x, end= " ") 

(array(10), array(20), array(30), array(40), array(50), array(60)) 

In [91]:
for int,x in np.ndenumerate(arrs):
    print(int,x)

NameError: name 'np' is not defined

In [90]:
#views vs copies.
# views changes the element of the original array while copies does not just as save and save as.
#views
arr = np.array([1,2,3,4,5])
views = arr[0:3]
views[2]= 23
print(arr)

NameError: name 'np' is not defined

In [89]:
#copies
copy = arr.copy()
copy[2]=4
print (copy)
print (arr)

[1 2 4 4 5]
[ 1  2 23  4  5]


In [98]:
#transpose
#this is used to swap rows with colums

arr = np.array([[1,2],[3,4]])
transpose = arr.transpose()
print(arr.transpose())
print (arr)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
